import express from "express";
import  {esignup}  from "../controller/auth.controller.js";
import { listingJob, listofJobs, listofJobsByid } from "../controller/joblist.controller.js";
import { verifyUser } from "../utils/userVerify.js";
const eauthRouter = express.Router();
eauthRouter.post('/esignup',esignup);
eauthRouter.post('/create',verifyUser,listingJob);
eauthRouter.get('/view/:id',verifyUser, listofJobs); 
eauthRouter.get('/view',verifyUser, listofJobs); 
eauthRouter.get('/viewbyid/:id', listofJobsByid); 
export default eauthRouter;